FROM node:24-slim AS build

RUN apt-get update -y && apt-get install -y openssl ca-certificates

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/

RUN npm install

COPY . .

RUN npx prisma generate
RUN npm run build

FROM node:24-slim

RUN apt-get update -y && apt-get install -y openssl ca-certificates
WORKDIR /app


COPY --from=build /app/dist ./dist
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/package*.json ./


ENV NODE_ENV=production
EXPOSE 3000
CMD ["npm", "run", "start"]