
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Study_session` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Study_session
 * 
 */
export type Study_sessionModel = runtime.Types.Result.DefaultSelection<Prisma.$Study_sessionPayload>

export type AggregateStudy_session = {
  _count: Study_sessionCountAggregateOutputType | null
  _avg: Study_sessionAvgAggregateOutputType | null
  _sum: Study_sessionSumAggregateOutputType | null
  _min: Study_sessionMinAggregateOutputType | null
  _max: Study_sessionMaxAggregateOutputType | null
}

export type Study_sessionAvgAggregateOutputType = {
  durantion_minutes: number | null
}

export type Study_sessionSumAggregateOutputType = {
  durantion_minutes: number | null
}

export type Study_sessionMinAggregateOutputType = {
  id: string | null
  topic: string | null
  durantion_minutes: number | null
  study_date: Date | null
  user_id: string | null
  subject_id: string | null
}

export type Study_sessionMaxAggregateOutputType = {
  id: string | null
  topic: string | null
  durantion_minutes: number | null
  study_date: Date | null
  user_id: string | null
  subject_id: string | null
}

export type Study_sessionCountAggregateOutputType = {
  id: number
  topic: number
  durantion_minutes: number
  study_date: number
  user_id: number
  subject_id: number
  _all: number
}


export type Study_sessionAvgAggregateInputType = {
  durantion_minutes?: true
}

export type Study_sessionSumAggregateInputType = {
  durantion_minutes?: true
}

export type Study_sessionMinAggregateInputType = {
  id?: true
  topic?: true
  durantion_minutes?: true
  study_date?: true
  user_id?: true
  subject_id?: true
}

export type Study_sessionMaxAggregateInputType = {
  id?: true
  topic?: true
  durantion_minutes?: true
  study_date?: true
  user_id?: true
  subject_id?: true
}

export type Study_sessionCountAggregateInputType = {
  id?: true
  topic?: true
  durantion_minutes?: true
  study_date?: true
  user_id?: true
  subject_id?: true
  _all?: true
}

export type Study_sessionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Study_session to aggregate.
   */
  where?: Prisma.Study_sessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Study_sessions to fetch.
   */
  orderBy?: Prisma.Study_sessionOrderByWithRelationInput | Prisma.Study_sessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.Study_sessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Study_sessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Study_sessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Study_sessions
  **/
  _count?: true | Study_sessionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Study_sessionAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Study_sessionSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Study_sessionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Study_sessionMaxAggregateInputType
}

export type GetStudy_sessionAggregateType<T extends Study_sessionAggregateArgs> = {
      [P in keyof T & keyof AggregateStudy_session]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateStudy_session[P]>
    : Prisma.GetScalarType<T[P], AggregateStudy_session[P]>
}




export type Study_sessionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.Study_sessionWhereInput
  orderBy?: Prisma.Study_sessionOrderByWithAggregationInput | Prisma.Study_sessionOrderByWithAggregationInput[]
  by: Prisma.Study_sessionScalarFieldEnum[] | Prisma.Study_sessionScalarFieldEnum
  having?: Prisma.Study_sessionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Study_sessionCountAggregateInputType | true
  _avg?: Study_sessionAvgAggregateInputType
  _sum?: Study_sessionSumAggregateInputType
  _min?: Study_sessionMinAggregateInputType
  _max?: Study_sessionMaxAggregateInputType
}

export type Study_sessionGroupByOutputType = {
  id: string
  topic: string
  durantion_minutes: number
  study_date: Date
  user_id: string
  subject_id: string
  _count: Study_sessionCountAggregateOutputType | null
  _avg: Study_sessionAvgAggregateOutputType | null
  _sum: Study_sessionSumAggregateOutputType | null
  _min: Study_sessionMinAggregateOutputType | null
  _max: Study_sessionMaxAggregateOutputType | null
}

export type GetStudy_sessionGroupByPayload<T extends Study_sessionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Study_sessionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Study_sessionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Study_sessionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Study_sessionGroupByOutputType[P]>
      }
    >
  >



export type Study_sessionWhereInput = {
  AND?: Prisma.Study_sessionWhereInput | Prisma.Study_sessionWhereInput[]
  OR?: Prisma.Study_sessionWhereInput[]
  NOT?: Prisma.Study_sessionWhereInput | Prisma.Study_sessionWhereInput[]
  id?: Prisma.StringFilter<"Study_session"> | string
  topic?: Prisma.StringFilter<"Study_session"> | string
  durantion_minutes?: Prisma.IntFilter<"Study_session"> | number
  study_date?: Prisma.DateTimeFilter<"Study_session"> | Date | string
  user_id?: Prisma.StringFilter<"Study_session"> | string
  subject_id?: Prisma.StringFilter<"Study_session"> | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  subject?: Prisma.XOR<Prisma.SubjectScalarRelationFilter, Prisma.SubjectWhereInput>
  revisions?: Prisma.RevisionListRelationFilter
}

export type Study_sessionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  topic?: Prisma.SortOrder
  durantion_minutes?: Prisma.SortOrder
  study_date?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  subject_id?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  subject?: Prisma.SubjectOrderByWithRelationInput
  revisions?: Prisma.RevisionOrderByRelationAggregateInput
}

export type Study_sessionWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.Study_sessionWhereInput | Prisma.Study_sessionWhereInput[]
  OR?: Prisma.Study_sessionWhereInput[]
  NOT?: Prisma.Study_sessionWhereInput | Prisma.Study_sessionWhereInput[]
  topic?: Prisma.StringFilter<"Study_session"> | string
  durantion_minutes?: Prisma.IntFilter<"Study_session"> | number
  study_date?: Prisma.DateTimeFilter<"Study_session"> | Date | string
  user_id?: Prisma.StringFilter<"Study_session"> | string
  subject_id?: Prisma.StringFilter<"Study_session"> | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  subject?: Prisma.XOR<Prisma.SubjectScalarRelationFilter, Prisma.SubjectWhereInput>
  revisions?: Prisma.RevisionListRelationFilter
}, "id">

export type Study_sessionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  topic?: Prisma.SortOrder
  durantion_minutes?: Prisma.SortOrder
  study_date?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  subject_id?: Prisma.SortOrder
  _count?: Prisma.Study_sessionCountOrderByAggregateInput
  _avg?: Prisma.Study_sessionAvgOrderByAggregateInput
  _max?: Prisma.Study_sessionMaxOrderByAggregateInput
  _min?: Prisma.Study_sessionMinOrderByAggregateInput
  _sum?: Prisma.Study_sessionSumOrderByAggregateInput
}

export type Study_sessionScalarWhereWithAggregatesInput = {
  AND?: Prisma.Study_sessionScalarWhereWithAggregatesInput | Prisma.Study_sessionScalarWhereWithAggregatesInput[]
  OR?: Prisma.Study_sessionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.Study_sessionScalarWhereWithAggregatesInput | Prisma.Study_sessionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Study_session"> | string
  topic?: Prisma.StringWithAggregatesFilter<"Study_session"> | string
  durantion_minutes?: Prisma.IntWithAggregatesFilter<"Study_session"> | number
  study_date?: Prisma.DateTimeWithAggregatesFilter<"Study_session"> | Date | string
  user_id?: Prisma.StringWithAggregatesFilter<"Study_session"> | string
  subject_id?: Prisma.StringWithAggregatesFilter<"Study_session"> | string
}

export type Study_sessionCreateInput = {
  id?: string
  topic: string
  durantion_minutes: number
  study_date: Date | string
  user: Prisma.UserCreateNestedOneWithoutStudy_sessionsInput
  subject: Prisma.SubjectCreateNestedOneWithoutStudy_sessionsInput
  revisions?: Prisma.RevisionCreateNestedManyWithoutStudyInput
}

export type Study_sessionUncheckedCreateInput = {
  id?: string
  topic: string
  durantion_minutes: number
  study_date: Date | string
  user_id: string
  subject_id: string
  revisions?: Prisma.RevisionUncheckedCreateNestedManyWithoutStudyInput
}

export type Study_sessionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  topic?: Prisma.StringFieldUpdateOperationsInput | string
  durantion_minutes?: Prisma.IntFieldUpdateOperationsInput | number
  study_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutStudy_sessionsNestedInput
  subject?: Prisma.SubjectUpdateOneRequiredWithoutStudy_sessionsNestedInput
  revisions?: Prisma.RevisionUpdateManyWithoutStudyNestedInput
}

export type Study_sessionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  topic?: Prisma.StringFieldUpdateOperationsInput | string
  durantion_minutes?: Prisma.IntFieldUpdateOperationsInput | number
  study_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  subject_id?: Prisma.StringFieldUpdateOperationsInput | string
  revisions?: Prisma.RevisionUncheckedUpdateManyWithoutStudyNestedInput
}

export type Study_sessionCreateManyInput = {
  id?: string
  topic: string
  durantion_minutes: number
  study_date: Date | string
  user_id: string
  subject_id: string
}

export type Study_sessionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  topic?: Prisma.StringFieldUpdateOperationsInput | string
  durantion_minutes?: Prisma.IntFieldUpdateOperationsInput | number
  study_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type Study_sessionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  topic?: Prisma.StringFieldUpdateOperationsInput | string
  durantion_minutes?: Prisma.IntFieldUpdateOperationsInput | number
  study_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  subject_id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type Study_sessionListRelationFilter = {
  every?: Prisma.Study_sessionWhereInput
  some?: Prisma.Study_sessionWhereInput
  none?: Prisma.Study_sessionWhereInput
}

export type Study_sessionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type Study_sessionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  topic?: Prisma.SortOrder
  durantion_minutes?: Prisma.SortOrder
  study_date?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  subject_id?: Prisma.SortOrder
}

export type Study_sessionAvgOrderByAggregateInput = {
  durantion_minutes?: Prisma.SortOrder
}

export type Study_sessionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  topic?: Prisma.SortOrder
  durantion_minutes?: Prisma.SortOrder
  study_date?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  subject_id?: Prisma.SortOrder
}

export type Study_sessionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  topic?: Prisma.SortOrder
  durantion_minutes?: Prisma.SortOrder
  study_date?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  subject_id?: Prisma.SortOrder
}

export type Study_sessionSumOrderByAggregateInput = {
  durantion_minutes?: Prisma.SortOrder
}

export type Study_sessionScalarRelationFilter = {
  is?: Prisma.Study_sessionWhereInput
  isNot?: Prisma.Study_sessionWhereInput
}

export type Study_sessionCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.Study_sessionCreateWithoutUserInput, Prisma.Study_sessionUncheckedCreateWithoutUserInput> | Prisma.Study_sessionCreateWithoutUserInput[] | Prisma.Study_sessionUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.Study_sessionCreateOrConnectWithoutUserInput | Prisma.Study_sessionCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.Study_sessionCreateManyUserInputEnvelope
  connect?: Prisma.Study_sessionWhereUniqueInput | Prisma.Study_sessionWhereUniqueInput[]
}

export type Study_sessionUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.Study_sessionCreateWithoutUserInput, Prisma.Study_sessionUncheckedCreateWithoutUserInput> | Prisma.Study_sessionCreateWithoutUserInput[] | Prisma.Study_sessionUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.Study_sessionCreateOrConnectWithoutUserInput | Prisma.Study_sessionCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.Study_sessionCreateManyUserInputEnvelope
  connect?: Prisma.Study_sessionWhereUniqueInput | Prisma.Study_sessionWhereUniqueInput[]
}

export type Study_sessionUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.Study_sessionCreateWithoutUserInput, Prisma.Study_sessionUncheckedCreateWithoutUserInput> | Prisma.Study_sessionCreateWithoutUserInput[] | Prisma.Study_sessionUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.Study_sessionCreateOrConnectWithoutUserInput | Prisma.Study_sessionCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.Study_sessionUpsertWithWhereUniqueWithoutUserInput | Prisma.Study_sessionUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.Study_sessionCreateManyUserInputEnvelope
  set?: Prisma.Study_sessionWhereUniqueInput | Prisma.Study_sessionWhereUniqueInput[]
  disconnect?: Prisma.Study_sessionWhereUniqueInput | Prisma.Study_sessionWhereUniqueInput[]
  delete?: Prisma.Study_sessionWhereUniqueInput | Prisma.Study_sessionWhereUniqueInput[]
  connect?: Prisma.Study_sessionWhereUniqueInput | Prisma.Study_sessionWhereUniqueInput[]
  update?: Prisma.Study_sessionUpdateWithWhereUniqueWithoutUserInput | Prisma.Study_sessionUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.Study_sessionUpdateManyWithWhereWithoutUserInput | Prisma.Study_sessionUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.Study_sessionScalarWhereInput | Prisma.Study_sessionScalarWhereInput[]
}

export type Study_sessionUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.Study_sessionCreateWithoutUserInput, Prisma.Study_sessionUncheckedCreateWithoutUserInput> | Prisma.Study_sessionCreateWithoutUserInput[] | Prisma.Study_sessionUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.Study_sessionCreateOrConnectWithoutUserInput | Prisma.Study_sessionCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.Study_sessionUpsertWithWhereUniqueWithoutUserInput | Prisma.Study_sessionUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.Study_sessionCreateManyUserInputEnvelope
  set?: Prisma.Study_sessionWhereUniqueInput | Prisma.Study_sessionWhereUniqueInput[]
  disconnect?: Prisma.Study_sessionWhereUniqueInput | Prisma.Study_sessionWhereUniqueInput[]
  delete?: Prisma.Study_sessionWhereUniqueInput | Prisma.Study_sessionWhereUniqueInput[]
  connect?: Prisma.Study_sessionWhereUniqueInput | Prisma.Study_sessionWhereUniqueInput[]
  update?: Prisma.Study_sessionUpdateWithWhereUniqueWithoutUserInput | Prisma.Study_sessionUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.Study_sessionUpdateManyWithWhereWithoutUserInput | Prisma.Study_sessionUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.Study_sessionScalarWhereInput | Prisma.Study_sessionScalarWhereInput[]
}

export type Study_sessionCreateNestedManyWithoutSubjectInput = {
  create?: Prisma.XOR<Prisma.Study_sessionCreateWithoutSubjectInput, Prisma.Study_sessionUncheckedCreateWithoutSubjectInput> | Prisma.Study_sessionCreateWithoutSubjectInput[] | Prisma.Study_sessionUncheckedCreateWithoutSubjectInput[]
  connectOrCreate?: Prisma.Study_sessionCreateOrConnectWithoutSubjectInput | Prisma.Study_sessionCreateOrConnectWithoutSubjectInput[]
  createMany?: Prisma.Study_sessionCreateManySubjectInputEnvelope
  connect?: Prisma.Study_sessionWhereUniqueInput | Prisma.Study_sessionWhereUniqueInput[]
}

export type Study_sessionUncheckedCreateNestedManyWithoutSubjectInput = {
  create?: Prisma.XOR<Prisma.Study_sessionCreateWithoutSubjectInput, Prisma.Study_sessionUncheckedCreateWithoutSubjectInput> | Prisma.Study_sessionCreateWithoutSubjectInput[] | Prisma.Study_sessionUncheckedCreateWithoutSubjectInput[]
  connectOrCreate?: Prisma.Study_sessionCreateOrConnectWithoutSubjectInput | Prisma.Study_sessionCreateOrConnectWithoutSubjectInput[]
  createMany?: Prisma.Study_sessionCreateManySubjectInputEnvelope
  connect?: Prisma.Study_sessionWhereUniqueInput | Prisma.Study_sessionWhereUniqueInput[]
}

export type Study_sessionUpdateManyWithoutSubjectNestedInput = {
  create?: Prisma.XOR<Prisma.Study_sessionCreateWithoutSubjectInput, Prisma.Study_sessionUncheckedCreateWithoutSubjectInput> | Prisma.Study_sessionCreateWithoutSubjectInput[] | Prisma.Study_sessionUncheckedCreateWithoutSubjectInput[]
  connectOrCreate?: Prisma.Study_sessionCreateOrConnectWithoutSubjectInput | Prisma.Study_sessionCreateOrConnectWithoutSubjectInput[]
  upsert?: Prisma.Study_sessionUpsertWithWhereUniqueWithoutSubjectInput | Prisma.Study_sessionUpsertWithWhereUniqueWithoutSubjectInput[]
  createMany?: Prisma.Study_sessionCreateManySubjectInputEnvelope
  set?: Prisma.Study_sessionWhereUniqueInput | Prisma.Study_sessionWhereUniqueInput[]
  disconnect?: Prisma.Study_sessionWhereUniqueInput | Prisma.Study_sessionWhereUniqueInput[]
  delete?: Prisma.Study_sessionWhereUniqueInput | Prisma.Study_sessionWhereUniqueInput[]
  connect?: Prisma.Study_sessionWhereUniqueInput | Prisma.Study_sessionWhereUniqueInput[]
  update?: Prisma.Study_sessionUpdateWithWhereUniqueWithoutSubjectInput | Prisma.Study_sessionUpdateWithWhereUniqueWithoutSubjectInput[]
  updateMany?: Prisma.Study_sessionUpdateManyWithWhereWithoutSubjectInput | Prisma.Study_sessionUpdateManyWithWhereWithoutSubjectInput[]
  deleteMany?: Prisma.Study_sessionScalarWhereInput | Prisma.Study_sessionScalarWhereInput[]
}

export type Study_sessionUncheckedUpdateManyWithoutSubjectNestedInput = {
  create?: Prisma.XOR<Prisma.Study_sessionCreateWithoutSubjectInput, Prisma.Study_sessionUncheckedCreateWithoutSubjectInput> | Prisma.Study_sessionCreateWithoutSubjectInput[] | Prisma.Study_sessionUncheckedCreateWithoutSubjectInput[]
  connectOrCreate?: Prisma.Study_sessionCreateOrConnectWithoutSubjectInput | Prisma.Study_sessionCreateOrConnectWithoutSubjectInput[]
  upsert?: Prisma.Study_sessionUpsertWithWhereUniqueWithoutSubjectInput | Prisma.Study_sessionUpsertWithWhereUniqueWithoutSubjectInput[]
  createMany?: Prisma.Study_sessionCreateManySubjectInputEnvelope
  set?: Prisma.Study_sessionWhereUniqueInput | Prisma.Study_sessionWhereUniqueInput[]
  disconnect?: Prisma.Study_sessionWhereUniqueInput | Prisma.Study_sessionWhereUniqueInput[]
  delete?: Prisma.Study_sessionWhereUniqueInput | Prisma.Study_sessionWhereUniqueInput[]
  connect?: Prisma.Study_sessionWhereUniqueInput | Prisma.Study_sessionWhereUniqueInput[]
  update?: Prisma.Study_sessionUpdateWithWhereUniqueWithoutSubjectInput | Prisma.Study_sessionUpdateWithWhereUniqueWithoutSubjectInput[]
  updateMany?: Prisma.Study_sessionUpdateManyWithWhereWithoutSubjectInput | Prisma.Study_sessionUpdateManyWithWhereWithoutSubjectInput[]
  deleteMany?: Prisma.Study_sessionScalarWhereInput | Prisma.Study_sessionScalarWhereInput[]
}

export type Study_sessionCreateNestedOneWithoutRevisionsInput = {
  create?: Prisma.XOR<Prisma.Study_sessionCreateWithoutRevisionsInput, Prisma.Study_sessionUncheckedCreateWithoutRevisionsInput>
  connectOrCreate?: Prisma.Study_sessionCreateOrConnectWithoutRevisionsInput
  connect?: Prisma.Study_sessionWhereUniqueInput
}

export type Study_sessionUpdateOneRequiredWithoutRevisionsNestedInput = {
  create?: Prisma.XOR<Prisma.Study_sessionCreateWithoutRevisionsInput, Prisma.Study_sessionUncheckedCreateWithoutRevisionsInput>
  connectOrCreate?: Prisma.Study_sessionCreateOrConnectWithoutRevisionsInput
  upsert?: Prisma.Study_sessionUpsertWithoutRevisionsInput
  connect?: Prisma.Study_sessionWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.Study_sessionUpdateToOneWithWhereWithoutRevisionsInput, Prisma.Study_sessionUpdateWithoutRevisionsInput>, Prisma.Study_sessionUncheckedUpdateWithoutRevisionsInput>
}

export type Study_sessionCreateWithoutUserInput = {
  id?: string
  topic: string
  durantion_minutes: number
  study_date: Date | string
  subject: Prisma.SubjectCreateNestedOneWithoutStudy_sessionsInput
  revisions?: Prisma.RevisionCreateNestedManyWithoutStudyInput
}

export type Study_sessionUncheckedCreateWithoutUserInput = {
  id?: string
  topic: string
  durantion_minutes: number
  study_date: Date | string
  subject_id: string
  revisions?: Prisma.RevisionUncheckedCreateNestedManyWithoutStudyInput
}

export type Study_sessionCreateOrConnectWithoutUserInput = {
  where: Prisma.Study_sessionWhereUniqueInput
  create: Prisma.XOR<Prisma.Study_sessionCreateWithoutUserInput, Prisma.Study_sessionUncheckedCreateWithoutUserInput>
}

export type Study_sessionCreateManyUserInputEnvelope = {
  data: Prisma.Study_sessionCreateManyUserInput | Prisma.Study_sessionCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type Study_sessionUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.Study_sessionWhereUniqueInput
  update: Prisma.XOR<Prisma.Study_sessionUpdateWithoutUserInput, Prisma.Study_sessionUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.Study_sessionCreateWithoutUserInput, Prisma.Study_sessionUncheckedCreateWithoutUserInput>
}

export type Study_sessionUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.Study_sessionWhereUniqueInput
  data: Prisma.XOR<Prisma.Study_sessionUpdateWithoutUserInput, Prisma.Study_sessionUncheckedUpdateWithoutUserInput>
}

export type Study_sessionUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.Study_sessionScalarWhereInput
  data: Prisma.XOR<Prisma.Study_sessionUpdateManyMutationInput, Prisma.Study_sessionUncheckedUpdateManyWithoutUserInput>
}

export type Study_sessionScalarWhereInput = {
  AND?: Prisma.Study_sessionScalarWhereInput | Prisma.Study_sessionScalarWhereInput[]
  OR?: Prisma.Study_sessionScalarWhereInput[]
  NOT?: Prisma.Study_sessionScalarWhereInput | Prisma.Study_sessionScalarWhereInput[]
  id?: Prisma.StringFilter<"Study_session"> | string
  topic?: Prisma.StringFilter<"Study_session"> | string
  durantion_minutes?: Prisma.IntFilter<"Study_session"> | number
  study_date?: Prisma.DateTimeFilter<"Study_session"> | Date | string
  user_id?: Prisma.StringFilter<"Study_session"> | string
  subject_id?: Prisma.StringFilter<"Study_session"> | string
}

export type Study_sessionCreateWithoutSubjectInput = {
  id?: string
  topic: string
  durantion_minutes: number
  study_date: Date | string
  user: Prisma.UserCreateNestedOneWithoutStudy_sessionsInput
  revisions?: Prisma.RevisionCreateNestedManyWithoutStudyInput
}

export type Study_sessionUncheckedCreateWithoutSubjectInput = {
  id?: string
  topic: string
  durantion_minutes: number
  study_date: Date | string
  user_id: string
  revisions?: Prisma.RevisionUncheckedCreateNestedManyWithoutStudyInput
}

export type Study_sessionCreateOrConnectWithoutSubjectInput = {
  where: Prisma.Study_sessionWhereUniqueInput
  create: Prisma.XOR<Prisma.Study_sessionCreateWithoutSubjectInput, Prisma.Study_sessionUncheckedCreateWithoutSubjectInput>
}

export type Study_sessionCreateManySubjectInputEnvelope = {
  data: Prisma.Study_sessionCreateManySubjectInput | Prisma.Study_sessionCreateManySubjectInput[]
  skipDuplicates?: boolean
}

export type Study_sessionUpsertWithWhereUniqueWithoutSubjectInput = {
  where: Prisma.Study_sessionWhereUniqueInput
  update: Prisma.XOR<Prisma.Study_sessionUpdateWithoutSubjectInput, Prisma.Study_sessionUncheckedUpdateWithoutSubjectInput>
  create: Prisma.XOR<Prisma.Study_sessionCreateWithoutSubjectInput, Prisma.Study_sessionUncheckedCreateWithoutSubjectInput>
}

export type Study_sessionUpdateWithWhereUniqueWithoutSubjectInput = {
  where: Prisma.Study_sessionWhereUniqueInput
  data: Prisma.XOR<Prisma.Study_sessionUpdateWithoutSubjectInput, Prisma.Study_sessionUncheckedUpdateWithoutSubjectInput>
}

export type Study_sessionUpdateManyWithWhereWithoutSubjectInput = {
  where: Prisma.Study_sessionScalarWhereInput
  data: Prisma.XOR<Prisma.Study_sessionUpdateManyMutationInput, Prisma.Study_sessionUncheckedUpdateManyWithoutSubjectInput>
}

export type Study_sessionCreateWithoutRevisionsInput = {
  id?: string
  topic: string
  durantion_minutes: number
  study_date: Date | string
  user: Prisma.UserCreateNestedOneWithoutStudy_sessionsInput
  subject: Prisma.SubjectCreateNestedOneWithoutStudy_sessionsInput
}

export type Study_sessionUncheckedCreateWithoutRevisionsInput = {
  id?: string
  topic: string
  durantion_minutes: number
  study_date: Date | string
  user_id: string
  subject_id: string
}

export type Study_sessionCreateOrConnectWithoutRevisionsInput = {
  where: Prisma.Study_sessionWhereUniqueInput
  create: Prisma.XOR<Prisma.Study_sessionCreateWithoutRevisionsInput, Prisma.Study_sessionUncheckedCreateWithoutRevisionsInput>
}

export type Study_sessionUpsertWithoutRevisionsInput = {
  update: Prisma.XOR<Prisma.Study_sessionUpdateWithoutRevisionsInput, Prisma.Study_sessionUncheckedUpdateWithoutRevisionsInput>
  create: Prisma.XOR<Prisma.Study_sessionCreateWithoutRevisionsInput, Prisma.Study_sessionUncheckedCreateWithoutRevisionsInput>
  where?: Prisma.Study_sessionWhereInput
}

export type Study_sessionUpdateToOneWithWhereWithoutRevisionsInput = {
  where?: Prisma.Study_sessionWhereInput
  data: Prisma.XOR<Prisma.Study_sessionUpdateWithoutRevisionsInput, Prisma.Study_sessionUncheckedUpdateWithoutRevisionsInput>
}

export type Study_sessionUpdateWithoutRevisionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  topic?: Prisma.StringFieldUpdateOperationsInput | string
  durantion_minutes?: Prisma.IntFieldUpdateOperationsInput | number
  study_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutStudy_sessionsNestedInput
  subject?: Prisma.SubjectUpdateOneRequiredWithoutStudy_sessionsNestedInput
}

export type Study_sessionUncheckedUpdateWithoutRevisionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  topic?: Prisma.StringFieldUpdateOperationsInput | string
  durantion_minutes?: Prisma.IntFieldUpdateOperationsInput | number
  study_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  subject_id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type Study_sessionCreateManyUserInput = {
  id?: string
  topic: string
  durantion_minutes: number
  study_date: Date | string
  subject_id: string
}

export type Study_sessionUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  topic?: Prisma.StringFieldUpdateOperationsInput | string
  durantion_minutes?: Prisma.IntFieldUpdateOperationsInput | number
  study_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  subject?: Prisma.SubjectUpdateOneRequiredWithoutStudy_sessionsNestedInput
  revisions?: Prisma.RevisionUpdateManyWithoutStudyNestedInput
}

export type Study_sessionUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  topic?: Prisma.StringFieldUpdateOperationsInput | string
  durantion_minutes?: Prisma.IntFieldUpdateOperationsInput | number
  study_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  subject_id?: Prisma.StringFieldUpdateOperationsInput | string
  revisions?: Prisma.RevisionUncheckedUpdateManyWithoutStudyNestedInput
}

export type Study_sessionUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  topic?: Prisma.StringFieldUpdateOperationsInput | string
  durantion_minutes?: Prisma.IntFieldUpdateOperationsInput | number
  study_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  subject_id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type Study_sessionCreateManySubjectInput = {
  id?: string
  topic: string
  durantion_minutes: number
  study_date: Date | string
  user_id: string
}

export type Study_sessionUpdateWithoutSubjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  topic?: Prisma.StringFieldUpdateOperationsInput | string
  durantion_minutes?: Prisma.IntFieldUpdateOperationsInput | number
  study_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutStudy_sessionsNestedInput
  revisions?: Prisma.RevisionUpdateManyWithoutStudyNestedInput
}

export type Study_sessionUncheckedUpdateWithoutSubjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  topic?: Prisma.StringFieldUpdateOperationsInput | string
  durantion_minutes?: Prisma.IntFieldUpdateOperationsInput | number
  study_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  revisions?: Prisma.RevisionUncheckedUpdateManyWithoutStudyNestedInput
}

export type Study_sessionUncheckedUpdateManyWithoutSubjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  topic?: Prisma.StringFieldUpdateOperationsInput | string
  durantion_minutes?: Prisma.IntFieldUpdateOperationsInput | number
  study_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type Study_sessionCountOutputType
 */

export type Study_sessionCountOutputType = {
  revisions: number
}

export type Study_sessionCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  revisions?: boolean | Study_sessionCountOutputTypeCountRevisionsArgs
}

/**
 * Study_sessionCountOutputType without action
 */
export type Study_sessionCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Study_sessionCountOutputType
   */
  select?: Prisma.Study_sessionCountOutputTypeSelect<ExtArgs> | null
}

/**
 * Study_sessionCountOutputType without action
 */
export type Study_sessionCountOutputTypeCountRevisionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RevisionWhereInput
}


export type Study_sessionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  topic?: boolean
  durantion_minutes?: boolean
  study_date?: boolean
  user_id?: boolean
  subject_id?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  subject?: boolean | Prisma.SubjectDefaultArgs<ExtArgs>
  revisions?: boolean | Prisma.Study_session$revisionsArgs<ExtArgs>
  _count?: boolean | Prisma.Study_sessionCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["study_session"]>

export type Study_sessionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  topic?: boolean
  durantion_minutes?: boolean
  study_date?: boolean
  user_id?: boolean
  subject_id?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  subject?: boolean | Prisma.SubjectDefaultArgs<ExtArgs>
}, ExtArgs["result"]["study_session"]>

export type Study_sessionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  topic?: boolean
  durantion_minutes?: boolean
  study_date?: boolean
  user_id?: boolean
  subject_id?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  subject?: boolean | Prisma.SubjectDefaultArgs<ExtArgs>
}, ExtArgs["result"]["study_session"]>

export type Study_sessionSelectScalar = {
  id?: boolean
  topic?: boolean
  durantion_minutes?: boolean
  study_date?: boolean
  user_id?: boolean
  subject_id?: boolean
}

export type Study_sessionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "topic" | "durantion_minutes" | "study_date" | "user_id" | "subject_id", ExtArgs["result"]["study_session"]>
export type Study_sessionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  subject?: boolean | Prisma.SubjectDefaultArgs<ExtArgs>
  revisions?: boolean | Prisma.Study_session$revisionsArgs<ExtArgs>
  _count?: boolean | Prisma.Study_sessionCountOutputTypeDefaultArgs<ExtArgs>
}
export type Study_sessionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  subject?: boolean | Prisma.SubjectDefaultArgs<ExtArgs>
}
export type Study_sessionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  subject?: boolean | Prisma.SubjectDefaultArgs<ExtArgs>
}

export type $Study_sessionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Study_session"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    subject: Prisma.$SubjectPayload<ExtArgs>
    revisions: Prisma.$RevisionPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    topic: string
    durantion_minutes: number
    study_date: Date
    user_id: string
    subject_id: string
  }, ExtArgs["result"]["study_session"]>
  composites: {}
}

export type Study_sessionGetPayload<S extends boolean | null | undefined | Study_sessionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$Study_sessionPayload, S>

export type Study_sessionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<Study_sessionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Study_sessionCountAggregateInputType | true
  }

export interface Study_sessionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Study_session'], meta: { name: 'Study_session' } }
  /**
   * Find zero or one Study_session that matches the filter.
   * @param {Study_sessionFindUniqueArgs} args - Arguments to find a Study_session
   * @example
   * // Get one Study_session
   * const study_session = await prisma.study_session.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends Study_sessionFindUniqueArgs>(args: Prisma.SelectSubset<T, Study_sessionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__Study_sessionClient<runtime.Types.Result.GetResult<Prisma.$Study_sessionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Study_session that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {Study_sessionFindUniqueOrThrowArgs} args - Arguments to find a Study_session
   * @example
   * // Get one Study_session
   * const study_session = await prisma.study_session.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends Study_sessionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, Study_sessionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__Study_sessionClient<runtime.Types.Result.GetResult<Prisma.$Study_sessionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Study_session that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Study_sessionFindFirstArgs} args - Arguments to find a Study_session
   * @example
   * // Get one Study_session
   * const study_session = await prisma.study_session.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends Study_sessionFindFirstArgs>(args?: Prisma.SelectSubset<T, Study_sessionFindFirstArgs<ExtArgs>>): Prisma.Prisma__Study_sessionClient<runtime.Types.Result.GetResult<Prisma.$Study_sessionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Study_session that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Study_sessionFindFirstOrThrowArgs} args - Arguments to find a Study_session
   * @example
   * // Get one Study_session
   * const study_session = await prisma.study_session.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends Study_sessionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, Study_sessionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__Study_sessionClient<runtime.Types.Result.GetResult<Prisma.$Study_sessionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Study_sessions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Study_sessionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Study_sessions
   * const study_sessions = await prisma.study_session.findMany()
   * 
   * // Get first 10 Study_sessions
   * const study_sessions = await prisma.study_session.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const study_sessionWithIdOnly = await prisma.study_session.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends Study_sessionFindManyArgs>(args?: Prisma.SelectSubset<T, Study_sessionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$Study_sessionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Study_session.
   * @param {Study_sessionCreateArgs} args - Arguments to create a Study_session.
   * @example
   * // Create one Study_session
   * const Study_session = await prisma.study_session.create({
   *   data: {
   *     // ... data to create a Study_session
   *   }
   * })
   * 
   */
  create<T extends Study_sessionCreateArgs>(args: Prisma.SelectSubset<T, Study_sessionCreateArgs<ExtArgs>>): Prisma.Prisma__Study_sessionClient<runtime.Types.Result.GetResult<Prisma.$Study_sessionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Study_sessions.
   * @param {Study_sessionCreateManyArgs} args - Arguments to create many Study_sessions.
   * @example
   * // Create many Study_sessions
   * const study_session = await prisma.study_session.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends Study_sessionCreateManyArgs>(args?: Prisma.SelectSubset<T, Study_sessionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Study_sessions and returns the data saved in the database.
   * @param {Study_sessionCreateManyAndReturnArgs} args - Arguments to create many Study_sessions.
   * @example
   * // Create many Study_sessions
   * const study_session = await prisma.study_session.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Study_sessions and only return the `id`
   * const study_sessionWithIdOnly = await prisma.study_session.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends Study_sessionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, Study_sessionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$Study_sessionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Study_session.
   * @param {Study_sessionDeleteArgs} args - Arguments to delete one Study_session.
   * @example
   * // Delete one Study_session
   * const Study_session = await prisma.study_session.delete({
   *   where: {
   *     // ... filter to delete one Study_session
   *   }
   * })
   * 
   */
  delete<T extends Study_sessionDeleteArgs>(args: Prisma.SelectSubset<T, Study_sessionDeleteArgs<ExtArgs>>): Prisma.Prisma__Study_sessionClient<runtime.Types.Result.GetResult<Prisma.$Study_sessionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Study_session.
   * @param {Study_sessionUpdateArgs} args - Arguments to update one Study_session.
   * @example
   * // Update one Study_session
   * const study_session = await prisma.study_session.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends Study_sessionUpdateArgs>(args: Prisma.SelectSubset<T, Study_sessionUpdateArgs<ExtArgs>>): Prisma.Prisma__Study_sessionClient<runtime.Types.Result.GetResult<Prisma.$Study_sessionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Study_sessions.
   * @param {Study_sessionDeleteManyArgs} args - Arguments to filter Study_sessions to delete.
   * @example
   * // Delete a few Study_sessions
   * const { count } = await prisma.study_session.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends Study_sessionDeleteManyArgs>(args?: Prisma.SelectSubset<T, Study_sessionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Study_sessions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Study_sessionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Study_sessions
   * const study_session = await prisma.study_session.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends Study_sessionUpdateManyArgs>(args: Prisma.SelectSubset<T, Study_sessionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Study_sessions and returns the data updated in the database.
   * @param {Study_sessionUpdateManyAndReturnArgs} args - Arguments to update many Study_sessions.
   * @example
   * // Update many Study_sessions
   * const study_session = await prisma.study_session.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Study_sessions and only return the `id`
   * const study_sessionWithIdOnly = await prisma.study_session.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends Study_sessionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, Study_sessionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$Study_sessionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Study_session.
   * @param {Study_sessionUpsertArgs} args - Arguments to update or create a Study_session.
   * @example
   * // Update or create a Study_session
   * const study_session = await prisma.study_session.upsert({
   *   create: {
   *     // ... data to create a Study_session
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Study_session we want to update
   *   }
   * })
   */
  upsert<T extends Study_sessionUpsertArgs>(args: Prisma.SelectSubset<T, Study_sessionUpsertArgs<ExtArgs>>): Prisma.Prisma__Study_sessionClient<runtime.Types.Result.GetResult<Prisma.$Study_sessionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Study_sessions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Study_sessionCountArgs} args - Arguments to filter Study_sessions to count.
   * @example
   * // Count the number of Study_sessions
   * const count = await prisma.study_session.count({
   *   where: {
   *     // ... the filter for the Study_sessions we want to count
   *   }
   * })
  **/
  count<T extends Study_sessionCountArgs>(
    args?: Prisma.Subset<T, Study_sessionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Study_sessionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Study_session.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Study_sessionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Study_sessionAggregateArgs>(args: Prisma.Subset<T, Study_sessionAggregateArgs>): Prisma.PrismaPromise<GetStudy_sessionAggregateType<T>>

  /**
   * Group by Study_session.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Study_sessionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends Study_sessionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: Study_sessionGroupByArgs['orderBy'] }
      : { orderBy?: Study_sessionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, Study_sessionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetStudy_sessionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Study_session model
 */
readonly fields: Study_sessionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Study_session.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__Study_sessionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  subject<T extends Prisma.SubjectDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SubjectDefaultArgs<ExtArgs>>): Prisma.Prisma__SubjectClient<runtime.Types.Result.GetResult<Prisma.$SubjectPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  revisions<T extends Prisma.Study_session$revisionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Study_session$revisionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RevisionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Study_session model
 */
export interface Study_sessionFieldRefs {
  readonly id: Prisma.FieldRef<"Study_session", 'String'>
  readonly topic: Prisma.FieldRef<"Study_session", 'String'>
  readonly durantion_minutes: Prisma.FieldRef<"Study_session", 'Int'>
  readonly study_date: Prisma.FieldRef<"Study_session", 'DateTime'>
  readonly user_id: Prisma.FieldRef<"Study_session", 'String'>
  readonly subject_id: Prisma.FieldRef<"Study_session", 'String'>
}
    

// Custom InputTypes
/**
 * Study_session findUnique
 */
export type Study_sessionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Study_session
   */
  select?: Prisma.Study_sessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Study_session
   */
  omit?: Prisma.Study_sessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Study_sessionInclude<ExtArgs> | null
  /**
   * Filter, which Study_session to fetch.
   */
  where: Prisma.Study_sessionWhereUniqueInput
}

/**
 * Study_session findUniqueOrThrow
 */
export type Study_sessionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Study_session
   */
  select?: Prisma.Study_sessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Study_session
   */
  omit?: Prisma.Study_sessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Study_sessionInclude<ExtArgs> | null
  /**
   * Filter, which Study_session to fetch.
   */
  where: Prisma.Study_sessionWhereUniqueInput
}

/**
 * Study_session findFirst
 */
export type Study_sessionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Study_session
   */
  select?: Prisma.Study_sessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Study_session
   */
  omit?: Prisma.Study_sessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Study_sessionInclude<ExtArgs> | null
  /**
   * Filter, which Study_session to fetch.
   */
  where?: Prisma.Study_sessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Study_sessions to fetch.
   */
  orderBy?: Prisma.Study_sessionOrderByWithRelationInput | Prisma.Study_sessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Study_sessions.
   */
  cursor?: Prisma.Study_sessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Study_sessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Study_sessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Study_sessions.
   */
  distinct?: Prisma.Study_sessionScalarFieldEnum | Prisma.Study_sessionScalarFieldEnum[]
}

/**
 * Study_session findFirstOrThrow
 */
export type Study_sessionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Study_session
   */
  select?: Prisma.Study_sessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Study_session
   */
  omit?: Prisma.Study_sessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Study_sessionInclude<ExtArgs> | null
  /**
   * Filter, which Study_session to fetch.
   */
  where?: Prisma.Study_sessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Study_sessions to fetch.
   */
  orderBy?: Prisma.Study_sessionOrderByWithRelationInput | Prisma.Study_sessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Study_sessions.
   */
  cursor?: Prisma.Study_sessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Study_sessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Study_sessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Study_sessions.
   */
  distinct?: Prisma.Study_sessionScalarFieldEnum | Prisma.Study_sessionScalarFieldEnum[]
}

/**
 * Study_session findMany
 */
export type Study_sessionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Study_session
   */
  select?: Prisma.Study_sessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Study_session
   */
  omit?: Prisma.Study_sessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Study_sessionInclude<ExtArgs> | null
  /**
   * Filter, which Study_sessions to fetch.
   */
  where?: Prisma.Study_sessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Study_sessions to fetch.
   */
  orderBy?: Prisma.Study_sessionOrderByWithRelationInput | Prisma.Study_sessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Study_sessions.
   */
  cursor?: Prisma.Study_sessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Study_sessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Study_sessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Study_sessions.
   */
  distinct?: Prisma.Study_sessionScalarFieldEnum | Prisma.Study_sessionScalarFieldEnum[]
}

/**
 * Study_session create
 */
export type Study_sessionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Study_session
   */
  select?: Prisma.Study_sessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Study_session
   */
  omit?: Prisma.Study_sessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Study_sessionInclude<ExtArgs> | null
  /**
   * The data needed to create a Study_session.
   */
  data: Prisma.XOR<Prisma.Study_sessionCreateInput, Prisma.Study_sessionUncheckedCreateInput>
}

/**
 * Study_session createMany
 */
export type Study_sessionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Study_sessions.
   */
  data: Prisma.Study_sessionCreateManyInput | Prisma.Study_sessionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Study_session createManyAndReturn
 */
export type Study_sessionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Study_session
   */
  select?: Prisma.Study_sessionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Study_session
   */
  omit?: Prisma.Study_sessionOmit<ExtArgs> | null
  /**
   * The data used to create many Study_sessions.
   */
  data: Prisma.Study_sessionCreateManyInput | Prisma.Study_sessionCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Study_sessionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Study_session update
 */
export type Study_sessionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Study_session
   */
  select?: Prisma.Study_sessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Study_session
   */
  omit?: Prisma.Study_sessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Study_sessionInclude<ExtArgs> | null
  /**
   * The data needed to update a Study_session.
   */
  data: Prisma.XOR<Prisma.Study_sessionUpdateInput, Prisma.Study_sessionUncheckedUpdateInput>
  /**
   * Choose, which Study_session to update.
   */
  where: Prisma.Study_sessionWhereUniqueInput
}

/**
 * Study_session updateMany
 */
export type Study_sessionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Study_sessions.
   */
  data: Prisma.XOR<Prisma.Study_sessionUpdateManyMutationInput, Prisma.Study_sessionUncheckedUpdateManyInput>
  /**
   * Filter which Study_sessions to update
   */
  where?: Prisma.Study_sessionWhereInput
  /**
   * Limit how many Study_sessions to update.
   */
  limit?: number
}

/**
 * Study_session updateManyAndReturn
 */
export type Study_sessionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Study_session
   */
  select?: Prisma.Study_sessionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Study_session
   */
  omit?: Prisma.Study_sessionOmit<ExtArgs> | null
  /**
   * The data used to update Study_sessions.
   */
  data: Prisma.XOR<Prisma.Study_sessionUpdateManyMutationInput, Prisma.Study_sessionUncheckedUpdateManyInput>
  /**
   * Filter which Study_sessions to update
   */
  where?: Prisma.Study_sessionWhereInput
  /**
   * Limit how many Study_sessions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Study_sessionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Study_session upsert
 */
export type Study_sessionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Study_session
   */
  select?: Prisma.Study_sessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Study_session
   */
  omit?: Prisma.Study_sessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Study_sessionInclude<ExtArgs> | null
  /**
   * The filter to search for the Study_session to update in case it exists.
   */
  where: Prisma.Study_sessionWhereUniqueInput
  /**
   * In case the Study_session found by the `where` argument doesn't exist, create a new Study_session with this data.
   */
  create: Prisma.XOR<Prisma.Study_sessionCreateInput, Prisma.Study_sessionUncheckedCreateInput>
  /**
   * In case the Study_session was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.Study_sessionUpdateInput, Prisma.Study_sessionUncheckedUpdateInput>
}

/**
 * Study_session delete
 */
export type Study_sessionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Study_session
   */
  select?: Prisma.Study_sessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Study_session
   */
  omit?: Prisma.Study_sessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Study_sessionInclude<ExtArgs> | null
  /**
   * Filter which Study_session to delete.
   */
  where: Prisma.Study_sessionWhereUniqueInput
}

/**
 * Study_session deleteMany
 */
export type Study_sessionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Study_sessions to delete
   */
  where?: Prisma.Study_sessionWhereInput
  /**
   * Limit how many Study_sessions to delete.
   */
  limit?: number
}

/**
 * Study_session.revisions
 */
export type Study_session$revisionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Revision
   */
  select?: Prisma.RevisionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Revision
   */
  omit?: Prisma.RevisionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RevisionInclude<ExtArgs> | null
  where?: Prisma.RevisionWhereInput
  orderBy?: Prisma.RevisionOrderByWithRelationInput | Prisma.RevisionOrderByWithRelationInput[]
  cursor?: Prisma.RevisionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.RevisionScalarFieldEnum | Prisma.RevisionScalarFieldEnum[]
}

/**
 * Study_session without action
 */
export type Study_sessionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Study_session
   */
  select?: Prisma.Study_sessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Study_session
   */
  omit?: Prisma.Study_sessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Study_sessionInclude<ExtArgs> | null
}
