
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Weekly_schedule` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Weekly_schedule
 * 
 */
export type Weekly_scheduleModel = runtime.Types.Result.DefaultSelection<Prisma.$Weekly_schedulePayload>

export type AggregateWeekly_schedule = {
  _count: Weekly_scheduleCountAggregateOutputType | null
  _avg: Weekly_scheduleAvgAggregateOutputType | null
  _sum: Weekly_scheduleSumAggregateOutputType | null
  _min: Weekly_scheduleMinAggregateOutputType | null
  _max: Weekly_scheduleMaxAggregateOutputType | null
}

export type Weekly_scheduleAvgAggregateOutputType = {
  day_of_week: number | null
}

export type Weekly_scheduleSumAggregateOutputType = {
  day_of_week: number | null
}

export type Weekly_scheduleMinAggregateOutputType = {
  id: string | null
  day_of_week: number | null
  user_id: string | null
}

export type Weekly_scheduleMaxAggregateOutputType = {
  id: string | null
  day_of_week: number | null
  user_id: string | null
}

export type Weekly_scheduleCountAggregateOutputType = {
  id: number
  day_of_week: number
  user_id: number
  _all: number
}


export type Weekly_scheduleAvgAggregateInputType = {
  day_of_week?: true
}

export type Weekly_scheduleSumAggregateInputType = {
  day_of_week?: true
}

export type Weekly_scheduleMinAggregateInputType = {
  id?: true
  day_of_week?: true
  user_id?: true
}

export type Weekly_scheduleMaxAggregateInputType = {
  id?: true
  day_of_week?: true
  user_id?: true
}

export type Weekly_scheduleCountAggregateInputType = {
  id?: true
  day_of_week?: true
  user_id?: true
  _all?: true
}

export type Weekly_scheduleAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Weekly_schedule to aggregate.
   */
  where?: Prisma.Weekly_scheduleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Weekly_schedules to fetch.
   */
  orderBy?: Prisma.Weekly_scheduleOrderByWithRelationInput | Prisma.Weekly_scheduleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.Weekly_scheduleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Weekly_schedules from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Weekly_schedules.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Weekly_schedules
  **/
  _count?: true | Weekly_scheduleCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Weekly_scheduleAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Weekly_scheduleSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Weekly_scheduleMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Weekly_scheduleMaxAggregateInputType
}

export type GetWeekly_scheduleAggregateType<T extends Weekly_scheduleAggregateArgs> = {
      [P in keyof T & keyof AggregateWeekly_schedule]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateWeekly_schedule[P]>
    : Prisma.GetScalarType<T[P], AggregateWeekly_schedule[P]>
}




export type Weekly_scheduleGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.Weekly_scheduleWhereInput
  orderBy?: Prisma.Weekly_scheduleOrderByWithAggregationInput | Prisma.Weekly_scheduleOrderByWithAggregationInput[]
  by: Prisma.Weekly_scheduleScalarFieldEnum[] | Prisma.Weekly_scheduleScalarFieldEnum
  having?: Prisma.Weekly_scheduleScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Weekly_scheduleCountAggregateInputType | true
  _avg?: Weekly_scheduleAvgAggregateInputType
  _sum?: Weekly_scheduleSumAggregateInputType
  _min?: Weekly_scheduleMinAggregateInputType
  _max?: Weekly_scheduleMaxAggregateInputType
}

export type Weekly_scheduleGroupByOutputType = {
  id: string
  day_of_week: number
  user_id: string
  _count: Weekly_scheduleCountAggregateOutputType | null
  _avg: Weekly_scheduleAvgAggregateOutputType | null
  _sum: Weekly_scheduleSumAggregateOutputType | null
  _min: Weekly_scheduleMinAggregateOutputType | null
  _max: Weekly_scheduleMaxAggregateOutputType | null
}

export type GetWeekly_scheduleGroupByPayload<T extends Weekly_scheduleGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Weekly_scheduleGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Weekly_scheduleGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Weekly_scheduleGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Weekly_scheduleGroupByOutputType[P]>
      }
    >
  >



export type Weekly_scheduleWhereInput = {
  AND?: Prisma.Weekly_scheduleWhereInput | Prisma.Weekly_scheduleWhereInput[]
  OR?: Prisma.Weekly_scheduleWhereInput[]
  NOT?: Prisma.Weekly_scheduleWhereInput | Prisma.Weekly_scheduleWhereInput[]
  id?: Prisma.StringFilter<"Weekly_schedule"> | string
  day_of_week?: Prisma.IntFilter<"Weekly_schedule"> | number
  user_id?: Prisma.StringFilter<"Weekly_schedule"> | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type Weekly_scheduleOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  day_of_week?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type Weekly_scheduleWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.Weekly_scheduleWhereInput | Prisma.Weekly_scheduleWhereInput[]
  OR?: Prisma.Weekly_scheduleWhereInput[]
  NOT?: Prisma.Weekly_scheduleWhereInput | Prisma.Weekly_scheduleWhereInput[]
  day_of_week?: Prisma.IntFilter<"Weekly_schedule"> | number
  user_id?: Prisma.StringFilter<"Weekly_schedule"> | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type Weekly_scheduleOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  day_of_week?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  _count?: Prisma.Weekly_scheduleCountOrderByAggregateInput
  _avg?: Prisma.Weekly_scheduleAvgOrderByAggregateInput
  _max?: Prisma.Weekly_scheduleMaxOrderByAggregateInput
  _min?: Prisma.Weekly_scheduleMinOrderByAggregateInput
  _sum?: Prisma.Weekly_scheduleSumOrderByAggregateInput
}

export type Weekly_scheduleScalarWhereWithAggregatesInput = {
  AND?: Prisma.Weekly_scheduleScalarWhereWithAggregatesInput | Prisma.Weekly_scheduleScalarWhereWithAggregatesInput[]
  OR?: Prisma.Weekly_scheduleScalarWhereWithAggregatesInput[]
  NOT?: Prisma.Weekly_scheduleScalarWhereWithAggregatesInput | Prisma.Weekly_scheduleScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Weekly_schedule"> | string
  day_of_week?: Prisma.IntWithAggregatesFilter<"Weekly_schedule"> | number
  user_id?: Prisma.StringWithAggregatesFilter<"Weekly_schedule"> | string
}

export type Weekly_scheduleCreateInput = {
  id?: string
  day_of_week: number
  user: Prisma.UserCreateNestedOneWithoutWeekly_schedulesInput
}

export type Weekly_scheduleUncheckedCreateInput = {
  id?: string
  day_of_week: number
  user_id: string
}

export type Weekly_scheduleUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  day_of_week?: Prisma.IntFieldUpdateOperationsInput | number
  user?: Prisma.UserUpdateOneRequiredWithoutWeekly_schedulesNestedInput
}

export type Weekly_scheduleUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  day_of_week?: Prisma.IntFieldUpdateOperationsInput | number
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type Weekly_scheduleCreateManyInput = {
  id?: string
  day_of_week: number
  user_id: string
}

export type Weekly_scheduleUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  day_of_week?: Prisma.IntFieldUpdateOperationsInput | number
}

export type Weekly_scheduleUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  day_of_week?: Prisma.IntFieldUpdateOperationsInput | number
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type Weekly_scheduleListRelationFilter = {
  every?: Prisma.Weekly_scheduleWhereInput
  some?: Prisma.Weekly_scheduleWhereInput
  none?: Prisma.Weekly_scheduleWhereInput
}

export type Weekly_scheduleOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type Weekly_scheduleCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  day_of_week?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
}

export type Weekly_scheduleAvgOrderByAggregateInput = {
  day_of_week?: Prisma.SortOrder
}

export type Weekly_scheduleMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  day_of_week?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
}

export type Weekly_scheduleMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  day_of_week?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
}

export type Weekly_scheduleSumOrderByAggregateInput = {
  day_of_week?: Prisma.SortOrder
}

export type Weekly_scheduleCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.Weekly_scheduleCreateWithoutUserInput, Prisma.Weekly_scheduleUncheckedCreateWithoutUserInput> | Prisma.Weekly_scheduleCreateWithoutUserInput[] | Prisma.Weekly_scheduleUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.Weekly_scheduleCreateOrConnectWithoutUserInput | Prisma.Weekly_scheduleCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.Weekly_scheduleCreateManyUserInputEnvelope
  connect?: Prisma.Weekly_scheduleWhereUniqueInput | Prisma.Weekly_scheduleWhereUniqueInput[]
}

export type Weekly_scheduleUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.Weekly_scheduleCreateWithoutUserInput, Prisma.Weekly_scheduleUncheckedCreateWithoutUserInput> | Prisma.Weekly_scheduleCreateWithoutUserInput[] | Prisma.Weekly_scheduleUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.Weekly_scheduleCreateOrConnectWithoutUserInput | Prisma.Weekly_scheduleCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.Weekly_scheduleCreateManyUserInputEnvelope
  connect?: Prisma.Weekly_scheduleWhereUniqueInput | Prisma.Weekly_scheduleWhereUniqueInput[]
}

export type Weekly_scheduleUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.Weekly_scheduleCreateWithoutUserInput, Prisma.Weekly_scheduleUncheckedCreateWithoutUserInput> | Prisma.Weekly_scheduleCreateWithoutUserInput[] | Prisma.Weekly_scheduleUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.Weekly_scheduleCreateOrConnectWithoutUserInput | Prisma.Weekly_scheduleCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.Weekly_scheduleUpsertWithWhereUniqueWithoutUserInput | Prisma.Weekly_scheduleUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.Weekly_scheduleCreateManyUserInputEnvelope
  set?: Prisma.Weekly_scheduleWhereUniqueInput | Prisma.Weekly_scheduleWhereUniqueInput[]
  disconnect?: Prisma.Weekly_scheduleWhereUniqueInput | Prisma.Weekly_scheduleWhereUniqueInput[]
  delete?: Prisma.Weekly_scheduleWhereUniqueInput | Prisma.Weekly_scheduleWhereUniqueInput[]
  connect?: Prisma.Weekly_scheduleWhereUniqueInput | Prisma.Weekly_scheduleWhereUniqueInput[]
  update?: Prisma.Weekly_scheduleUpdateWithWhereUniqueWithoutUserInput | Prisma.Weekly_scheduleUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.Weekly_scheduleUpdateManyWithWhereWithoutUserInput | Prisma.Weekly_scheduleUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.Weekly_scheduleScalarWhereInput | Prisma.Weekly_scheduleScalarWhereInput[]
}

export type Weekly_scheduleUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.Weekly_scheduleCreateWithoutUserInput, Prisma.Weekly_scheduleUncheckedCreateWithoutUserInput> | Prisma.Weekly_scheduleCreateWithoutUserInput[] | Prisma.Weekly_scheduleUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.Weekly_scheduleCreateOrConnectWithoutUserInput | Prisma.Weekly_scheduleCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.Weekly_scheduleUpsertWithWhereUniqueWithoutUserInput | Prisma.Weekly_scheduleUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.Weekly_scheduleCreateManyUserInputEnvelope
  set?: Prisma.Weekly_scheduleWhereUniqueInput | Prisma.Weekly_scheduleWhereUniqueInput[]
  disconnect?: Prisma.Weekly_scheduleWhereUniqueInput | Prisma.Weekly_scheduleWhereUniqueInput[]
  delete?: Prisma.Weekly_scheduleWhereUniqueInput | Prisma.Weekly_scheduleWhereUniqueInput[]
  connect?: Prisma.Weekly_scheduleWhereUniqueInput | Prisma.Weekly_scheduleWhereUniqueInput[]
  update?: Prisma.Weekly_scheduleUpdateWithWhereUniqueWithoutUserInput | Prisma.Weekly_scheduleUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.Weekly_scheduleUpdateManyWithWhereWithoutUserInput | Prisma.Weekly_scheduleUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.Weekly_scheduleScalarWhereInput | Prisma.Weekly_scheduleScalarWhereInput[]
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type Weekly_scheduleCreateWithoutUserInput = {
  id?: string
  day_of_week: number
}

export type Weekly_scheduleUncheckedCreateWithoutUserInput = {
  id?: string
  day_of_week: number
}

export type Weekly_scheduleCreateOrConnectWithoutUserInput = {
  where: Prisma.Weekly_scheduleWhereUniqueInput
  create: Prisma.XOR<Prisma.Weekly_scheduleCreateWithoutUserInput, Prisma.Weekly_scheduleUncheckedCreateWithoutUserInput>
}

export type Weekly_scheduleCreateManyUserInputEnvelope = {
  data: Prisma.Weekly_scheduleCreateManyUserInput | Prisma.Weekly_scheduleCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type Weekly_scheduleUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.Weekly_scheduleWhereUniqueInput
  update: Prisma.XOR<Prisma.Weekly_scheduleUpdateWithoutUserInput, Prisma.Weekly_scheduleUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.Weekly_scheduleCreateWithoutUserInput, Prisma.Weekly_scheduleUncheckedCreateWithoutUserInput>
}

export type Weekly_scheduleUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.Weekly_scheduleWhereUniqueInput
  data: Prisma.XOR<Prisma.Weekly_scheduleUpdateWithoutUserInput, Prisma.Weekly_scheduleUncheckedUpdateWithoutUserInput>
}

export type Weekly_scheduleUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.Weekly_scheduleScalarWhereInput
  data: Prisma.XOR<Prisma.Weekly_scheduleUpdateManyMutationInput, Prisma.Weekly_scheduleUncheckedUpdateManyWithoutUserInput>
}

export type Weekly_scheduleScalarWhereInput = {
  AND?: Prisma.Weekly_scheduleScalarWhereInput | Prisma.Weekly_scheduleScalarWhereInput[]
  OR?: Prisma.Weekly_scheduleScalarWhereInput[]
  NOT?: Prisma.Weekly_scheduleScalarWhereInput | Prisma.Weekly_scheduleScalarWhereInput[]
  id?: Prisma.StringFilter<"Weekly_schedule"> | string
  day_of_week?: Prisma.IntFilter<"Weekly_schedule"> | number
  user_id?: Prisma.StringFilter<"Weekly_schedule"> | string
}

export type Weekly_scheduleCreateManyUserInput = {
  id?: string
  day_of_week: number
}

export type Weekly_scheduleUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  day_of_week?: Prisma.IntFieldUpdateOperationsInput | number
}

export type Weekly_scheduleUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  day_of_week?: Prisma.IntFieldUpdateOperationsInput | number
}

export type Weekly_scheduleUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  day_of_week?: Prisma.IntFieldUpdateOperationsInput | number
}



export type Weekly_scheduleSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  day_of_week?: boolean
  user_id?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["weekly_schedule"]>

export type Weekly_scheduleSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  day_of_week?: boolean
  user_id?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["weekly_schedule"]>

export type Weekly_scheduleSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  day_of_week?: boolean
  user_id?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["weekly_schedule"]>

export type Weekly_scheduleSelectScalar = {
  id?: boolean
  day_of_week?: boolean
  user_id?: boolean
}

export type Weekly_scheduleOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "day_of_week" | "user_id", ExtArgs["result"]["weekly_schedule"]>
export type Weekly_scheduleInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type Weekly_scheduleIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type Weekly_scheduleIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $Weekly_schedulePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Weekly_schedule"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    day_of_week: number
    user_id: string
  }, ExtArgs["result"]["weekly_schedule"]>
  composites: {}
}

export type Weekly_scheduleGetPayload<S extends boolean | null | undefined | Weekly_scheduleDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$Weekly_schedulePayload, S>

export type Weekly_scheduleCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<Weekly_scheduleFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Weekly_scheduleCountAggregateInputType | true
  }

export interface Weekly_scheduleDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Weekly_schedule'], meta: { name: 'Weekly_schedule' } }
  /**
   * Find zero or one Weekly_schedule that matches the filter.
   * @param {Weekly_scheduleFindUniqueArgs} args - Arguments to find a Weekly_schedule
   * @example
   * // Get one Weekly_schedule
   * const weekly_schedule = await prisma.weekly_schedule.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends Weekly_scheduleFindUniqueArgs>(args: Prisma.SelectSubset<T, Weekly_scheduleFindUniqueArgs<ExtArgs>>): Prisma.Prisma__Weekly_scheduleClient<runtime.Types.Result.GetResult<Prisma.$Weekly_schedulePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Weekly_schedule that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {Weekly_scheduleFindUniqueOrThrowArgs} args - Arguments to find a Weekly_schedule
   * @example
   * // Get one Weekly_schedule
   * const weekly_schedule = await prisma.weekly_schedule.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends Weekly_scheduleFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, Weekly_scheduleFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__Weekly_scheduleClient<runtime.Types.Result.GetResult<Prisma.$Weekly_schedulePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Weekly_schedule that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Weekly_scheduleFindFirstArgs} args - Arguments to find a Weekly_schedule
   * @example
   * // Get one Weekly_schedule
   * const weekly_schedule = await prisma.weekly_schedule.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends Weekly_scheduleFindFirstArgs>(args?: Prisma.SelectSubset<T, Weekly_scheduleFindFirstArgs<ExtArgs>>): Prisma.Prisma__Weekly_scheduleClient<runtime.Types.Result.GetResult<Prisma.$Weekly_schedulePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Weekly_schedule that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Weekly_scheduleFindFirstOrThrowArgs} args - Arguments to find a Weekly_schedule
   * @example
   * // Get one Weekly_schedule
   * const weekly_schedule = await prisma.weekly_schedule.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends Weekly_scheduleFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, Weekly_scheduleFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__Weekly_scheduleClient<runtime.Types.Result.GetResult<Prisma.$Weekly_schedulePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Weekly_schedules that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Weekly_scheduleFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Weekly_schedules
   * const weekly_schedules = await prisma.weekly_schedule.findMany()
   * 
   * // Get first 10 Weekly_schedules
   * const weekly_schedules = await prisma.weekly_schedule.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const weekly_scheduleWithIdOnly = await prisma.weekly_schedule.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends Weekly_scheduleFindManyArgs>(args?: Prisma.SelectSubset<T, Weekly_scheduleFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$Weekly_schedulePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Weekly_schedule.
   * @param {Weekly_scheduleCreateArgs} args - Arguments to create a Weekly_schedule.
   * @example
   * // Create one Weekly_schedule
   * const Weekly_schedule = await prisma.weekly_schedule.create({
   *   data: {
   *     // ... data to create a Weekly_schedule
   *   }
   * })
   * 
   */
  create<T extends Weekly_scheduleCreateArgs>(args: Prisma.SelectSubset<T, Weekly_scheduleCreateArgs<ExtArgs>>): Prisma.Prisma__Weekly_scheduleClient<runtime.Types.Result.GetResult<Prisma.$Weekly_schedulePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Weekly_schedules.
   * @param {Weekly_scheduleCreateManyArgs} args - Arguments to create many Weekly_schedules.
   * @example
   * // Create many Weekly_schedules
   * const weekly_schedule = await prisma.weekly_schedule.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends Weekly_scheduleCreateManyArgs>(args?: Prisma.SelectSubset<T, Weekly_scheduleCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Weekly_schedules and returns the data saved in the database.
   * @param {Weekly_scheduleCreateManyAndReturnArgs} args - Arguments to create many Weekly_schedules.
   * @example
   * // Create many Weekly_schedules
   * const weekly_schedule = await prisma.weekly_schedule.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Weekly_schedules and only return the `id`
   * const weekly_scheduleWithIdOnly = await prisma.weekly_schedule.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends Weekly_scheduleCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, Weekly_scheduleCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$Weekly_schedulePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Weekly_schedule.
   * @param {Weekly_scheduleDeleteArgs} args - Arguments to delete one Weekly_schedule.
   * @example
   * // Delete one Weekly_schedule
   * const Weekly_schedule = await prisma.weekly_schedule.delete({
   *   where: {
   *     // ... filter to delete one Weekly_schedule
   *   }
   * })
   * 
   */
  delete<T extends Weekly_scheduleDeleteArgs>(args: Prisma.SelectSubset<T, Weekly_scheduleDeleteArgs<ExtArgs>>): Prisma.Prisma__Weekly_scheduleClient<runtime.Types.Result.GetResult<Prisma.$Weekly_schedulePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Weekly_schedule.
   * @param {Weekly_scheduleUpdateArgs} args - Arguments to update one Weekly_schedule.
   * @example
   * // Update one Weekly_schedule
   * const weekly_schedule = await prisma.weekly_schedule.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends Weekly_scheduleUpdateArgs>(args: Prisma.SelectSubset<T, Weekly_scheduleUpdateArgs<ExtArgs>>): Prisma.Prisma__Weekly_scheduleClient<runtime.Types.Result.GetResult<Prisma.$Weekly_schedulePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Weekly_schedules.
   * @param {Weekly_scheduleDeleteManyArgs} args - Arguments to filter Weekly_schedules to delete.
   * @example
   * // Delete a few Weekly_schedules
   * const { count } = await prisma.weekly_schedule.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends Weekly_scheduleDeleteManyArgs>(args?: Prisma.SelectSubset<T, Weekly_scheduleDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Weekly_schedules.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Weekly_scheduleUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Weekly_schedules
   * const weekly_schedule = await prisma.weekly_schedule.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends Weekly_scheduleUpdateManyArgs>(args: Prisma.SelectSubset<T, Weekly_scheduleUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Weekly_schedules and returns the data updated in the database.
   * @param {Weekly_scheduleUpdateManyAndReturnArgs} args - Arguments to update many Weekly_schedules.
   * @example
   * // Update many Weekly_schedules
   * const weekly_schedule = await prisma.weekly_schedule.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Weekly_schedules and only return the `id`
   * const weekly_scheduleWithIdOnly = await prisma.weekly_schedule.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends Weekly_scheduleUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, Weekly_scheduleUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$Weekly_schedulePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Weekly_schedule.
   * @param {Weekly_scheduleUpsertArgs} args - Arguments to update or create a Weekly_schedule.
   * @example
   * // Update or create a Weekly_schedule
   * const weekly_schedule = await prisma.weekly_schedule.upsert({
   *   create: {
   *     // ... data to create a Weekly_schedule
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Weekly_schedule we want to update
   *   }
   * })
   */
  upsert<T extends Weekly_scheduleUpsertArgs>(args: Prisma.SelectSubset<T, Weekly_scheduleUpsertArgs<ExtArgs>>): Prisma.Prisma__Weekly_scheduleClient<runtime.Types.Result.GetResult<Prisma.$Weekly_schedulePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Weekly_schedules.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Weekly_scheduleCountArgs} args - Arguments to filter Weekly_schedules to count.
   * @example
   * // Count the number of Weekly_schedules
   * const count = await prisma.weekly_schedule.count({
   *   where: {
   *     // ... the filter for the Weekly_schedules we want to count
   *   }
   * })
  **/
  count<T extends Weekly_scheduleCountArgs>(
    args?: Prisma.Subset<T, Weekly_scheduleCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Weekly_scheduleCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Weekly_schedule.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Weekly_scheduleAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Weekly_scheduleAggregateArgs>(args: Prisma.Subset<T, Weekly_scheduleAggregateArgs>): Prisma.PrismaPromise<GetWeekly_scheduleAggregateType<T>>

  /**
   * Group by Weekly_schedule.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Weekly_scheduleGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends Weekly_scheduleGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: Weekly_scheduleGroupByArgs['orderBy'] }
      : { orderBy?: Weekly_scheduleGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, Weekly_scheduleGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetWeekly_scheduleGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Weekly_schedule model
 */
readonly fields: Weekly_scheduleFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Weekly_schedule.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__Weekly_scheduleClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Weekly_schedule model
 */
export interface Weekly_scheduleFieldRefs {
  readonly id: Prisma.FieldRef<"Weekly_schedule", 'String'>
  readonly day_of_week: Prisma.FieldRef<"Weekly_schedule", 'Int'>
  readonly user_id: Prisma.FieldRef<"Weekly_schedule", 'String'>
}
    

// Custom InputTypes
/**
 * Weekly_schedule findUnique
 */
export type Weekly_scheduleFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Weekly_schedule
   */
  select?: Prisma.Weekly_scheduleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Weekly_schedule
   */
  omit?: Prisma.Weekly_scheduleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Weekly_scheduleInclude<ExtArgs> | null
  /**
   * Filter, which Weekly_schedule to fetch.
   */
  where: Prisma.Weekly_scheduleWhereUniqueInput
}

/**
 * Weekly_schedule findUniqueOrThrow
 */
export type Weekly_scheduleFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Weekly_schedule
   */
  select?: Prisma.Weekly_scheduleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Weekly_schedule
   */
  omit?: Prisma.Weekly_scheduleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Weekly_scheduleInclude<ExtArgs> | null
  /**
   * Filter, which Weekly_schedule to fetch.
   */
  where: Prisma.Weekly_scheduleWhereUniqueInput
}

/**
 * Weekly_schedule findFirst
 */
export type Weekly_scheduleFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Weekly_schedule
   */
  select?: Prisma.Weekly_scheduleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Weekly_schedule
   */
  omit?: Prisma.Weekly_scheduleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Weekly_scheduleInclude<ExtArgs> | null
  /**
   * Filter, which Weekly_schedule to fetch.
   */
  where?: Prisma.Weekly_scheduleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Weekly_schedules to fetch.
   */
  orderBy?: Prisma.Weekly_scheduleOrderByWithRelationInput | Prisma.Weekly_scheduleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Weekly_schedules.
   */
  cursor?: Prisma.Weekly_scheduleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Weekly_schedules from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Weekly_schedules.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Weekly_schedules.
   */
  distinct?: Prisma.Weekly_scheduleScalarFieldEnum | Prisma.Weekly_scheduleScalarFieldEnum[]
}

/**
 * Weekly_schedule findFirstOrThrow
 */
export type Weekly_scheduleFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Weekly_schedule
   */
  select?: Prisma.Weekly_scheduleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Weekly_schedule
   */
  omit?: Prisma.Weekly_scheduleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Weekly_scheduleInclude<ExtArgs> | null
  /**
   * Filter, which Weekly_schedule to fetch.
   */
  where?: Prisma.Weekly_scheduleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Weekly_schedules to fetch.
   */
  orderBy?: Prisma.Weekly_scheduleOrderByWithRelationInput | Prisma.Weekly_scheduleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Weekly_schedules.
   */
  cursor?: Prisma.Weekly_scheduleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Weekly_schedules from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Weekly_schedules.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Weekly_schedules.
   */
  distinct?: Prisma.Weekly_scheduleScalarFieldEnum | Prisma.Weekly_scheduleScalarFieldEnum[]
}

/**
 * Weekly_schedule findMany
 */
export type Weekly_scheduleFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Weekly_schedule
   */
  select?: Prisma.Weekly_scheduleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Weekly_schedule
   */
  omit?: Prisma.Weekly_scheduleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Weekly_scheduleInclude<ExtArgs> | null
  /**
   * Filter, which Weekly_schedules to fetch.
   */
  where?: Prisma.Weekly_scheduleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Weekly_schedules to fetch.
   */
  orderBy?: Prisma.Weekly_scheduleOrderByWithRelationInput | Prisma.Weekly_scheduleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Weekly_schedules.
   */
  cursor?: Prisma.Weekly_scheduleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Weekly_schedules from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Weekly_schedules.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Weekly_schedules.
   */
  distinct?: Prisma.Weekly_scheduleScalarFieldEnum | Prisma.Weekly_scheduleScalarFieldEnum[]
}

/**
 * Weekly_schedule create
 */
export type Weekly_scheduleCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Weekly_schedule
   */
  select?: Prisma.Weekly_scheduleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Weekly_schedule
   */
  omit?: Prisma.Weekly_scheduleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Weekly_scheduleInclude<ExtArgs> | null
  /**
   * The data needed to create a Weekly_schedule.
   */
  data: Prisma.XOR<Prisma.Weekly_scheduleCreateInput, Prisma.Weekly_scheduleUncheckedCreateInput>
}

/**
 * Weekly_schedule createMany
 */
export type Weekly_scheduleCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Weekly_schedules.
   */
  data: Prisma.Weekly_scheduleCreateManyInput | Prisma.Weekly_scheduleCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Weekly_schedule createManyAndReturn
 */
export type Weekly_scheduleCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Weekly_schedule
   */
  select?: Prisma.Weekly_scheduleSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Weekly_schedule
   */
  omit?: Prisma.Weekly_scheduleOmit<ExtArgs> | null
  /**
   * The data used to create many Weekly_schedules.
   */
  data: Prisma.Weekly_scheduleCreateManyInput | Prisma.Weekly_scheduleCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Weekly_scheduleIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Weekly_schedule update
 */
export type Weekly_scheduleUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Weekly_schedule
   */
  select?: Prisma.Weekly_scheduleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Weekly_schedule
   */
  omit?: Prisma.Weekly_scheduleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Weekly_scheduleInclude<ExtArgs> | null
  /**
   * The data needed to update a Weekly_schedule.
   */
  data: Prisma.XOR<Prisma.Weekly_scheduleUpdateInput, Prisma.Weekly_scheduleUncheckedUpdateInput>
  /**
   * Choose, which Weekly_schedule to update.
   */
  where: Prisma.Weekly_scheduleWhereUniqueInput
}

/**
 * Weekly_schedule updateMany
 */
export type Weekly_scheduleUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Weekly_schedules.
   */
  data: Prisma.XOR<Prisma.Weekly_scheduleUpdateManyMutationInput, Prisma.Weekly_scheduleUncheckedUpdateManyInput>
  /**
   * Filter which Weekly_schedules to update
   */
  where?: Prisma.Weekly_scheduleWhereInput
  /**
   * Limit how many Weekly_schedules to update.
   */
  limit?: number
}

/**
 * Weekly_schedule updateManyAndReturn
 */
export type Weekly_scheduleUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Weekly_schedule
   */
  select?: Prisma.Weekly_scheduleSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Weekly_schedule
   */
  omit?: Prisma.Weekly_scheduleOmit<ExtArgs> | null
  /**
   * The data used to update Weekly_schedules.
   */
  data: Prisma.XOR<Prisma.Weekly_scheduleUpdateManyMutationInput, Prisma.Weekly_scheduleUncheckedUpdateManyInput>
  /**
   * Filter which Weekly_schedules to update
   */
  where?: Prisma.Weekly_scheduleWhereInput
  /**
   * Limit how many Weekly_schedules to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Weekly_scheduleIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Weekly_schedule upsert
 */
export type Weekly_scheduleUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Weekly_schedule
   */
  select?: Prisma.Weekly_scheduleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Weekly_schedule
   */
  omit?: Prisma.Weekly_scheduleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Weekly_scheduleInclude<ExtArgs> | null
  /**
   * The filter to search for the Weekly_schedule to update in case it exists.
   */
  where: Prisma.Weekly_scheduleWhereUniqueInput
  /**
   * In case the Weekly_schedule found by the `where` argument doesn't exist, create a new Weekly_schedule with this data.
   */
  create: Prisma.XOR<Prisma.Weekly_scheduleCreateInput, Prisma.Weekly_scheduleUncheckedCreateInput>
  /**
   * In case the Weekly_schedule was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.Weekly_scheduleUpdateInput, Prisma.Weekly_scheduleUncheckedUpdateInput>
}

/**
 * Weekly_schedule delete
 */
export type Weekly_scheduleDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Weekly_schedule
   */
  select?: Prisma.Weekly_scheduleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Weekly_schedule
   */
  omit?: Prisma.Weekly_scheduleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Weekly_scheduleInclude<ExtArgs> | null
  /**
   * Filter which Weekly_schedule to delete.
   */
  where: Prisma.Weekly_scheduleWhereUniqueInput
}

/**
 * Weekly_schedule deleteMany
 */
export type Weekly_scheduleDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Weekly_schedules to delete
   */
  where?: Prisma.Weekly_scheduleWhereInput
  /**
   * Limit how many Weekly_schedules to delete.
   */
  limit?: number
}

/**
 * Weekly_schedule without action
 */
export type Weekly_scheduleDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Weekly_schedule
   */
  select?: Prisma.Weekly_scheduleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Weekly_schedule
   */
  omit?: Prisma.Weekly_scheduleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Weekly_scheduleInclude<ExtArgs> | null
}
