
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/User.js'
export type * from './models/Subject.js'
export type * from './models/Weekly_schedule.js'
export type * from './models/Study_session.js'
export type * from './models/Revision.js'
export type * from './commonInputTypes.js'